// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Associated struct {
	ID              int32
	Asscname        string
	Logoimage       string
	Asscdescription string
	Email           string
	Contactnumber   string
	Pix             string
	Street          string
	Descriptionaddr string
}
