// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAssociated = `-- name: DeleteAssociated :exec
DELETE FROM associateds_table WHERE id = $1
`

func (q *Queries) DeleteAssociated(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAssociated, id)
	return err
}

const getAssociateds = `-- name: GetAssociateds :many
SELECT id, logoimage, asscdescription, email, contactnumber, pix, street, descriptionaddr FROM associateds_table ORDER BY id LIMIT $1
`

func (q *Queries) GetAssociateds(ctx context.Context, limit int32) ([]AssociatedsTable, error) {
	rows, err := q.db.QueryContext(ctx, getAssociateds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssociatedsTable
	for rows.Next() {
		var i AssociatedsTable
		if err := rows.Scan(
			&i.ID,
			&i.Logoimage,
			&i.Asscdescription,
			&i.Email,
			&i.Contactnumber,
			&i.Pix,
			&i.Street,
			&i.Descriptionaddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssociatedsFromLocation = `-- name: GetAssociatedsFromLocation :many
SELECT id, logoimage, asscdescription, email, contactnumber, pix, street, descriptionaddr FROM associateds_table WHERE descriptionAddr LIKE '%' || $1 || '%' ORDER BY id
`

func (q *Queries) GetAssociatedsFromLocation(ctx context.Context, dollar_1 sql.NullString) ([]AssociatedsTable, error) {
	rows, err := q.db.QueryContext(ctx, getAssociatedsFromLocation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssociatedsTable
	for rows.Next() {
		var i AssociatedsTable
		if err := rows.Scan(
			&i.ID,
			&i.Logoimage,
			&i.Asscdescription,
			&i.Email,
			&i.Contactnumber,
			&i.Pix,
			&i.Street,
			&i.Descriptionaddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssociatedsInverted = `-- name: GetAssociatedsInverted :many
SELECT id, logoimage, asscdescription, email, contactnumber, pix, street, descriptionaddr FROM associateds_table ORDER BY id DESC
`

func (q *Queries) GetAssociatedsInverted(ctx context.Context) ([]AssociatedsTable, error) {
	rows, err := q.db.QueryContext(ctx, getAssociatedsInverted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssociatedsTable
	for rows.Next() {
		var i AssociatedsTable
		if err := rows.Scan(
			&i.ID,
			&i.Logoimage,
			&i.Asscdescription,
			&i.Email,
			&i.Contactnumber,
			&i.Pix,
			&i.Street,
			&i.Descriptionaddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAssociated = `-- name: InsertAssociated :exec
INSERT INTO associateds_table (logoImage, asscDescription, email, contactNumber, pix, street, descriptionAddr) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAssociatedParams struct {
	Logoimage       string
	Asscdescription string
	Email           string
	Contactnumber   string
	Pix             string
	Street          string
	Descriptionaddr string
}

func (q *Queries) InsertAssociated(ctx context.Context, arg InsertAssociatedParams) error {
	_, err := q.db.ExecContext(ctx, insertAssociated,
		arg.Logoimage,
		arg.Asscdescription,
		arg.Email,
		arg.Contactnumber,
		arg.Pix,
		arg.Street,
		arg.Descriptionaddr,
	)
	return err
}

const updateAssociated = `-- name: UpdateAssociated :exec
UPDATE associateds_table SET logoImage = $1, asscDescription = $2, email = $3, contactNumber = $4, pix = $5, street = $6, descriptionAddr = $7 WHERE id = $8
`

type UpdateAssociatedParams struct {
	Logoimage       string
	Asscdescription string
	Email           string
	Contactnumber   string
	Pix             string
	Street          string
	Descriptionaddr string
	ID              int32
}

func (q *Queries) UpdateAssociated(ctx context.Context, arg UpdateAssociatedParams) error {
	_, err := q.db.ExecContext(ctx, updateAssociated,
		arg.Logoimage,
		arg.Asscdescription,
		arg.Email,
		arg.Contactnumber,
		arg.Pix,
		arg.Street,
		arg.Descriptionaddr,
		arg.ID,
	)
	return err
}
